# Generated by Django 3.1.7 on 2021-04-09 12:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=True, verbose_name='This is a field for completed')),
                ('title', models.CharField(default=False, max_length=50)),
                ('datefield', models.DateField(default=django.utils.timezone.now)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.EmailField(max_length=40)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('integer', models.IntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('positive_small_integer', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
