# Generated by Django 3.1.7 on 2021-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
